package com.teamursamajor.auto;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class PathWriter {
	
	public PathWriter(Path[] paths, String filename) {
		writePath(paths, filename);
	}
	
	public void writePath(Path[] paths, String filename) {
		String newLine = System.lineSeparator();
		String toWrite = "# Ursa Major-style Path file generated by PathWriter.java" + newLine + "# Name:" + newLine;
		toWrite += paths[0].getName().substring(0, paths[0].getName().length() - 4) + newLine;
		toWrite += "# Number of points:" + newLine;
		toWrite += paths[0].numPoints() + newLine;
		toWrite += "# Left path:" + newLine;
		toWrite += "left" + newLine;
		toWrite += "# TIME (s) | DIST (ft) | HEADING (deg) | VEL (ft/s) | ACC (ft/s^2) |   X (ft)  |   Y(ft)" + newLine;
		for (PointonPath point : paths[0].getPoints()) {
			toWrite += point.toString() + newLine;
		}
		toWrite += "end" + newLine + newLine;
		toWrite += "# Right path:" + newLine;
		toWrite += "right" + newLine;
		for (PointonPath point : paths[1].getPoints()) {
			toWrite += point.toString() + newLine;
		}
		toWrite += "end";
		try {
			Files.write(Paths.get(System.getProperty("user.dir") + "\\" + filename), toWrite.getBytes());
		} catch (IOException e) {
			e.printStackTrace();
		}
	}


}
