package com.teamursamajor.auto.OldCode;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.Path;

public class PathWriter {
	
	public PathWriter(RobotPath[] RobotPaths, String filename) {
		writePath(RobotPaths, filename);
	}
	
	public void writePath(RobotPath[] RobotPaths, String filename) {
		String newLine = System.lineSeparator();
		String toWrite = "# Ursa Major-style Path file generated by PathWriter.java" + newLine + "# Name:" + newLine;
		toWrite += RobotPaths[0].getName().substring(0, RobotPaths[0].getName().length() - 4) + newLine;
		toWrite += "# Number of points:" + newLine;
		toWrite += RobotPaths[0].numPoints() + newLine;
		toWrite += "# Left path:" + newLine;
		toWrite += "left" + newLine;
		toWrite += "# TIME (s) | DIST (ft) | HEADING (deg) | VEL (ft/s) | ACC (ft/s^2) |   X (ft)  |   Y(ft)" + newLine;
		for (PointonPath point : RobotPaths[0].getPoints()) {
			toWrite += point.toString() + newLine;
		}
		toWrite += "end" + newLine + newLine;
		toWrite += "# Right path:" + newLine;
		toWrite += "right" + newLine;
		for (PointonPath point : RobotPaths[1].getPoints()) {
			toWrite += point.toString() + newLine;
		}
		toWrite += "end";
		try {
			//Files.write(RobotPaths.get(System.getProperty("user.dir") + "\\" + filename), toWrite.getBytes());
			Path filePath = Paths.get("C:/Users/teamursamajor/Desktop/PathMakerTESTING.txt");
			Files.write(filePath, toWrite.getBytes());
			
			//Files.write(System."C:/Users/teamursamajor/Desktop/PathMakerTESTING.txt", toWrite.getBytes());

		} catch (IOException e) {
			e.printStackTrace();
		}
	}


}
