import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class PathWriter {
	
	public PathWriter(Path[] paths, String filename) {
		writePath(paths, filename);
	}
	
	public void writePath(Path[] paths, String filename) {
		String toWrite = "# Ursa Major-style Path file generated by PathWriter.java\n# Name:\n";
		toWrite += paths[0].getName().substring(0, paths[0].getName().length() - 4) + '\n';
		toWrite += "# Number of points:\n";
		toWrite += paths[0].numPoints() + '\n';
		toWrite += "# Left path:\n";
		toWrite += "# DIST (ft) | HEADING (deg) | X (ft) | Y(ft)\n";
		for (PointonPath point : paths[0].getPoints()) {
			toWrite += point.toString() + '\n';
		}
		toWrite += "end\n\n";
		toWrite += "# Right path:\n";
		for (PointonPath point : paths[1].getPoints()) {
			toWrite += point.toString() + '\n';
		}
		toWrite += "end";
		try {
			Files.write(Paths.get(System.getProperty("user.dir") + "\\" + filename), toWrite.getBytes());
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

}
